/**                 ***COPYRIGHT STARTS HERE***
 *  BoutTime - the wrestling tournament administrator.
 *
 *  Copyright (C) 2009  Jeffrey K. Rutt
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *                  ***COPYRIGHT ENDS HERE***                                */

package bouttime.wizard.newtournament;

import org.netbeans.spi.wizard.WizardPage;

/**
 * 
 */
public class TournamentValuesForm extends WizardPage {

    /** Creates new form TournamentValuesForm */
    public TournamentValuesForm() {
        initComponents();
    }

    public static final String getDescription() {
        return "Enter values";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        header2Label = new javax.swing.JLabel();
        divLabel = new javax.swing.JLabel();
        classificationLabel = new javax.swing.JLabel();
        weightClassLabel = new javax.swing.JLabel();
        matLabel = new javax.swing.JLabel();
        sessionLabel = new javax.swing.JLabel();
        boutTimeLabel = new javax.swing.JLabel();
        classifications = new javax.swing.JTextField();
        divisions = new javax.swing.JTextField();
        weightClasses = new javax.swing.JTextField();
        mats = new javax.swing.JTextField();
        sessions = new javax.swing.JTextField();
        boutTimes = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bouttime.mainview.BoutTimeApp.class).getContext().getResourceMap(TournamentValuesForm.class);
        header1Label.setText(resourceMap.getString("header1Label.text")); // NOI18N
        header1Label.setName("header1Label"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        header2Label.setText(resourceMap.getString("header2Label.text")); // NOI18N
        header2Label.setName("header2Label"); // NOI18N

        divLabel.setText(resourceMap.getString("divLabel.text")); // NOI18N
        divLabel.setName("divLabel"); // NOI18N

        classificationLabel.setText(resourceMap.getString("classificationLabel.text")); // NOI18N
        classificationLabel.setName("classificationLabel"); // NOI18N

        weightClassLabel.setText(resourceMap.getString("weightClassLabel.text")); // NOI18N
        weightClassLabel.setName("weightClassLabel"); // NOI18N

        matLabel.setText(resourceMap.getString("matLabel.text")); // NOI18N
        matLabel.setName("matLabel"); // NOI18N

        sessionLabel.setText(resourceMap.getString("sessionLabel.text")); // NOI18N
        sessionLabel.setName("sessionLabel"); // NOI18N

        boutTimeLabel.setText(resourceMap.getString("boutTimeLabel.text")); // NOI18N
        boutTimeLabel.setName("boutTimeLabel"); // NOI18N

        classifications.setText(resourceMap.getString("classifications.text")); // NOI18N
        classifications.setToolTipText(resourceMap.getString("classifications.toolTipText")); // NOI18N
        classifications.setName("classifications"); // NOI18N
        classifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificationsActionPerformed(evt);
            }
        });

        divisions.setText(resourceMap.getString("divisions.text")); // NOI18N
        divisions.setToolTipText(resourceMap.getString("divisions.toolTipText")); // NOI18N
        divisions.setName("divisions"); // NOI18N

        weightClasses.setText(resourceMap.getString("weightClasses.text")); // NOI18N
        weightClasses.setToolTipText(resourceMap.getString("weightClasses.toolTipText")); // NOI18N
        weightClasses.setName("weightClasses"); // NOI18N

        mats.setText(resourceMap.getString("mats.text")); // NOI18N
        mats.setToolTipText(resourceMap.getString("mats.toolTipText")); // NOI18N
        mats.setName("mats"); // NOI18N

        sessions.setText(resourceMap.getString("sessions.text")); // NOI18N
        sessions.setToolTipText(resourceMap.getString("sessions.toolTipText")); // NOI18N
        sessions.setName("sessions"); // NOI18N

        boutTimes.setText(resourceMap.getString("boutTimes.text")); // NOI18N
        boutTimes.setToolTipText(resourceMap.getString("boutTimes.toolTipText")); // NOI18N
        boutTimes.setName("boutTimes"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boutTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sessionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weightClassLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(divLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(classificationLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divisions, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(classifications, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(weightClasses, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(mats, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(sessions, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(boutTimes, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(header2Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(header1Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classificationLabel)
                    .addComponent(classifications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divLabel)
                    .addComponent(divisions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightClassLabel)
                    .addComponent(weightClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matLabel)
                    .addComponent(mats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionLabel)
                    .addComponent(sessions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutTimeLabel)
                    .addComponent(boutTimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classificationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boutTimeLabel;
    private javax.swing.JTextField boutTimes;
    private javax.swing.JLabel classificationLabel;
    private javax.swing.JTextField classifications;
    private javax.swing.JLabel divLabel;
    private javax.swing.JTextField divisions;
    private javax.swing.JLabel header1Label;
    private javax.swing.JLabel header2Label;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel matLabel;
    private javax.swing.JTextField mats;
    private javax.swing.JLabel sessionLabel;
    private javax.swing.JTextField sessions;
    private javax.swing.JLabel weightClassLabel;
    private javax.swing.JTextField weightClasses;
    // End of variables declaration//GEN-END:variables

}
