/**                 ***COPYRIGHT STARTS HERE***
 *  BoutTime - the wrestling tournament administrator.
 *
 *  Copyright (C) 2010  Jeffrey K. Rutt
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *                  ***COPYRIGHT ENDS HERE***                                */

package bouttime.gui.panel;

import bouttime.mainview.BoutTimeView;
import bouttime.model.Group;

/**
 * A class that contains the graphical components to administer the various
 * parts of the groups in a tournament.  This includes the group filter panel
 * which provides a filtered list of groups, the bout list panel, the bracket
 * preview, the wrestler list (for setting seed values and place values), and
 * statistics panels.
 */
public class GroupPanel extends javax.swing.JPanel {

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * No-arg constructor to make netBeans GUI builder happy.  In order to
     * add this class to the Palette, you are required to have a no-arg
     * constructor.  There is no other need for this, so don't use it.
     * @deprecated
     */
    public GroupPanel() {this(null);}

    /** Creates new form GroupPanel */
    public GroupPanel(BoutTimeView v) {
        super();

        this.view = v;
        
        initComponents();
    }

    ////////////////////////////////////////////////////////////////////////////
    // Class Methods
    ////////////////////////////////////////////////////////////////////////////

    /**
     * A group selection has changed.  Notify the "child" panels so they can
     * update themselves.
     * @param g
     */
    public void groupSelectionChanged(Group g) {
        groupWrestlerListPanel.updateList(g);
        bracketPreviewPanel.updatePanel(g,
                (this.view == null) ? null : this.view.getDao());
        boutListPanel.updateList(g);
    }

    /**
     * A group has changed.  Notify the group list panel so it can update itself.
     * @param g
     */
    public void groupChanged(Group g) {
        groupListFilterPanel.updateGroup(g);
    }

    /**
     * Notify the "child" panels to update their statistics.
     */
    public void refreshStats() {
        wrestlerByClassDiv.updateStats();
        boutsByDivision.updateStats();
        boutsBySessionMat.updateStats();
        boutsByMat.updateStats();
        wrestlerByClassDivChart.updateStats();
        boutsByDivisionChart.updateStats();
        boutsBySessionMatChart.updateStats();
        boutsByMatChart.updateStats();
    }

    /**
     * A Dao property change has occurred.  Notify the "child" panels so that
     * they can update themselves.
     */
    public void daoPropertyChange() {
        // groupWrestlerListPanel.daoPropertyChange() will update the
        // other panels.
        groupListFilterPanel.daoPropertyChange();
        groupWrestlerListPanel.daoPropertyChange();
    }

    /**
     * Update the list in the group list filter panel.
     */
    public void updateGroupList() {
        groupListFilterPanel.updateList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        groupWrestlerListPanel = new bouttime.gui.panel.GroupWrestlerListPanel(this.view);
        jTabbedPane3 = new javax.swing.JTabbedPane();
        wrestlerByClassDiv = new bouttime.gui.panel.WrestlersByClassDiv(this.view);
        boutsByDivision = new bouttime.gui.panel.BoutsByDivision(this.view);
        boutsBySessionMat = new bouttime.gui.panel.BoutsBySessionMat(this.view);
        boutsByMat = new bouttime.gui.panel.BoutsByMat(this.view);
        jTabbedPane4 = new javax.swing.JTabbedPane();
        wrestlerByClassDivChart = new bouttime.gui.panel.WrestlersByClassDivChart(this.view);
        boutsByDivisionChart = new bouttime.gui.panel.BoutsByDivisionChart(this.view);
        boutsBySessionMatChart = new bouttime.gui.panel.BoutsBySessionMatChart(this.view);
        boutsByMatChart = new bouttime.gui.panel.BoutsByMatChart(this.view);
        groupListFilterPanel = new bouttime.gui.panel.GroupListFilterPanel(this.view);
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bracketPreviewPanel = new bouttime.gui.panel.BracketPreviewPanel();
        boutListPanel = new bouttime.gui.panel.BoutListPanel(this.view);

        setName("Form"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setName("jSplitPane2"); // NOI18N

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        groupWrestlerListPanel.setName("groupWrestlerListPanel"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bouttime.mainview.BoutTimeApp.class).getContext().getResourceMap(GroupPanel.class);
        jTabbedPane2.addTab(resourceMap.getString("groupWrestlerListPanel.TabConstraints.tabTitle"), groupWrestlerListPanel); // NOI18N

        jTabbedPane3.setName("jTabbedPane3"); // NOI18N

        wrestlerByClassDiv.setName("wrestlerByClassDiv"); // NOI18N
        jTabbedPane3.addTab(resourceMap.getString("wrestlerByClassDiv.TabConstraints.tabTitle"), wrestlerByClassDiv); // NOI18N

        boutsByDivision.setName("boutsByDivision"); // NOI18N
        jTabbedPane3.addTab(resourceMap.getString("boutsByDivision.TabConstraints.tabTitle"), boutsByDivision); // NOI18N

        boutsBySessionMat.setName("boutsBySessionMat"); // NOI18N
        jTabbedPane3.addTab(resourceMap.getString("boutsBySessionMat.TabConstraints.tabTitle"), boutsBySessionMat); // NOI18N

        boutsByMat.setName("boutsByMat"); // NOI18N
        jTabbedPane3.addTab(resourceMap.getString("boutsByMat.TabConstraints.tabTitle"), boutsByMat); // NOI18N

        jTabbedPane2.addTab(resourceMap.getString("jTabbedPane3.TabConstraints.tabTitle"), jTabbedPane3); // NOI18N

        jTabbedPane4.setName("jTabbedPane4"); // NOI18N

        wrestlerByClassDivChart.setName("wrestlerByClassDivChart"); // NOI18N
        jTabbedPane4.addTab(resourceMap.getString("wrestlerByClassDivChart.TabConstraints.tabTitle"), wrestlerByClassDivChart); // NOI18N

        boutsByDivisionChart.setName("boutsByDivisionChart"); // NOI18N

        javax.swing.GroupLayout boutsByDivisionChartLayout = new javax.swing.GroupLayout(boutsByDivisionChart);
        boutsByDivisionChart.setLayout(boutsByDivisionChartLayout);
        boutsByDivisionChartLayout.setHorizontalGroup(
            boutsByDivisionChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        boutsByDivisionChartLayout.setVerticalGroup(
            boutsByDivisionChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab(resourceMap.getString("boutsByDivisionChart.TabConstraints.tabTitle"), boutsByDivisionChart); // NOI18N

        boutsBySessionMatChart.setName("boutsBySessionMatChart"); // NOI18N

        javax.swing.GroupLayout boutsBySessionMatChartLayout = new javax.swing.GroupLayout(boutsBySessionMatChart);
        boutsBySessionMatChart.setLayout(boutsBySessionMatChartLayout);
        boutsBySessionMatChartLayout.setHorizontalGroup(
            boutsBySessionMatChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        boutsBySessionMatChartLayout.setVerticalGroup(
            boutsBySessionMatChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab(resourceMap.getString("boutsBySessionMatChart.TabConstraints.tabTitle"), boutsBySessionMatChart); // NOI18N

        boutsByMatChart.setName("boutsByMatChart"); // NOI18N

        javax.swing.GroupLayout boutsByMatChartLayout = new javax.swing.GroupLayout(boutsByMatChart);
        boutsByMatChart.setLayout(boutsByMatChartLayout);
        boutsByMatChartLayout.setHorizontalGroup(
            boutsByMatChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        boutsByMatChartLayout.setVerticalGroup(
            boutsByMatChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab(resourceMap.getString("boutsByMatChart.TabConstraints.tabTitle"), boutsByMatChart); // NOI18N

        jTabbedPane2.addTab(resourceMap.getString("jTabbedPane4.TabConstraints.tabTitle"), jTabbedPane4); // NOI18N

        jSplitPane2.setBottomComponent(jTabbedPane2);

        groupListFilterPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("groupListFilterPanel.border.title"))); // NOI18N
        groupListFilterPanel.setName("groupListFilterPanel"); // NOI18N
        jSplitPane2.setLeftComponent(groupListFilterPanel);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        bracketPreviewPanel.setName("bracketPreviewPanel"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("bracketPreviewPanel.TabConstraints.tabTitle"), bracketPreviewPanel); // NOI18N

        boutListPanel.setName("boutListPanel"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("boutListPanel.TabConstraints.tabTitle"), boutListPanel); // NOI18N

        jSplitPane1.setRightComponent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bouttime.gui.panel.BoutListPanel boutListPanel;
    private bouttime.gui.panel.BoutsByDivision boutsByDivision;
    private bouttime.gui.panel.BoutsByDivisionChart boutsByDivisionChart;
    private bouttime.gui.panel.BoutsByMat boutsByMat;
    private bouttime.gui.panel.BoutsByMatChart boutsByMatChart;
    private bouttime.gui.panel.BoutsBySessionMat boutsBySessionMat;
    private bouttime.gui.panel.BoutsBySessionMatChart boutsBySessionMatChart;
    private bouttime.gui.panel.BracketPreviewPanel bracketPreviewPanel;
    private bouttime.gui.panel.GroupListFilterPanel groupListFilterPanel;
    private bouttime.gui.panel.GroupWrestlerListPanel groupWrestlerListPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private bouttime.gui.panel.WrestlersByClassDiv wrestlerByClassDiv;
    private bouttime.gui.panel.WrestlersByClassDivChart wrestlerByClassDivChart;
    // End of variables declaration//GEN-END:variables

    private BoutTimeView view;
}
