/**                 ***COPYRIGHT STARTS HERE***
 *  BoutTime - the wrestling tournament administrator.
 *
 *  Copyright (C) 2009  Jeffrey K. Rutt
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *                  ***COPYRIGHT ENDS HERE***                                */

package bouttime.wizard.fileinput.xml;

import bouttime.fileinput.XMLFileInputConfig;
import java.awt.Component;
import org.netbeans.spi.wizard.WizardPage;

/**
 * This class implements a wizard page to specify the document root element and
 * wrestler element(s) in the input file.
 */
public class XmlElementStringSelector extends WizardPage {

    /** Creates new form XmlElementStringSelector */
    public XmlElementStringSelector(XMLFileInputConfig config) {
        initComponents();
        initValues(config);
    }

    public static final String getDescription() {
        return "Enter XML document strings";
    }

    /**
     * Validate the contents of the input.
     * The user must enter values for the root element and the wrestler element.
     * @param component
     * @param o
     * @return Help message or null (if contents are valid).
     */
    @Override
    protected String validateContents (Component component, Object o) {
        if (root.getText().isEmpty()) {
            return "You must provide a string for the document's root element";
        } else if (wrestler.getText().isEmpty()) {
            return "You must provide a string for the wrestler elements";
        }

        return null;
    }
    
    /**
     * Initialize the values of the graphical components.
     * @param config FileInputConfig object containing the current configuration.
     */
    private void initValues(XMLFileInputConfig config) {
        String s;

        s = config.getRoot();
        if (s != null) {
            root.setText(s);
        }

        s = config.getWrestler();
        if (s != null) {
            wrestler.setText(s);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1Label = new javax.swing.JLabel();
        header2Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rootLabel = new javax.swing.JLabel();
        root = new javax.swing.JTextField();
        wrestlerLabel = new javax.swing.JLabel();
        wrestler = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(bouttime.mainview.BoutTimeApp.class).getContext().getResourceMap(XmlElementStringSelector.class);
        header1Label.setText(resourceMap.getString("header1Label.text")); // NOI18N
        header1Label.setName("header1Label"); // NOI18N

        header2Label.setText(resourceMap.getString("header2Label.text")); // NOI18N
        header2Label.setName("header2Label"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        rootLabel.setText(resourceMap.getString("rootLabel.text")); // NOI18N
        rootLabel.setName("rootLabel"); // NOI18N

        root.setName("root"); // NOI18N

        wrestlerLabel.setText(resourceMap.getString("wrestlerLabel.text")); // NOI18N
        wrestlerLabel.setName("wrestlerLabel"); // NOI18N

        wrestler.setName("wrestler"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rootLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wrestlerLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wrestler)
                            .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addComponent(header1Label)
                    .addComponent(header2Label))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rootLabel)
                    .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrestlerLabel)
                    .addComponent(wrestler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header1Label;
    private javax.swing.JLabel header2Label;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField root;
    private javax.swing.JLabel rootLabel;
    private javax.swing.JTextField wrestler;
    private javax.swing.JLabel wrestlerLabel;
    // End of variables declaration//GEN-END:variables

}
